# Generated by Django 4.2.3 on 2024-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='MeetSites/')),
                ('url', models.URLField(blank=True)),
                ('nombre_visiteurs_par_mois', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('Généraliste', 'Je cherche un site généraliste'), ('Libertin', 'Je cherche un site libertin'), ('Non déterminé', 'Je cherche tout le monde'), ('Senior', 'Je cherche un site pour senior'), ('Extra-conjugales', 'Je cherche un site extra-conjugal'), ('Tchat', 'Je cherche un tchat instantané'), ('Haut-de-gamme', 'Je cherche un site haut-de-gamme'), ('Religion', 'Je cherche un site soutenant une religion'), ('Handicap', 'Je cherche un site à destination du handicap'), ('Locale', 'Je cherche un site locale'), ('Insolite', 'Je cherche un site insolite'), ('Géolocalisation', 'Je cherche un site axé sur la géolocalisation')], default='Non déterminé', max_length=25)),
                ('pourcent_femmes', models.CharField(choices=[('absence de femmes', 'Absence de femmes'), ('bas', 'Bas'), ('moyen', 'Moyen'), ('élevé', 'Élevé'), ('integral', 'Intégral')], max_length=50)),
                ('age', models.CharField(choices=[('18-25', '18-25 ans'), ('25-35', '25-35 ans'), ('35-45', '35-45 ans'), ('45-55', '45-55 ans'), ('plus', 'Plus de 55 ans')], max_length=50)),
                ('prix_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('google_trustpilot_avg', models.FloatField(blank=True, null=True)),
                ('affiliation', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notre site de rencontre partenaire',
                'verbose_name_plural': 'Nos sites de rencontres partenaires',
            },
        ),
    ]
