# Generated by Django 4.2.11 on 2024-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('url', models.URLField()),
                ('non_affilie', models.BooleanField(default=False)),
                ('categorie', models.CharField(max_length=100)),
                ('nombre_visiteurs_par_mois', models.IntegerField()),
                ('pourcentage_femmes', models.FloatField()),
                ('tranche_age', models.CharField(max_length=50)),
                ('durabilite', models.CharField(max_length=50)),
                ('qualite_du_site', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('ranking', models.PositiveIntegerField()),
                ('partner_logo', models.ImageField(upload_to='partner_logos/')),
                ('google_trustpilot_avg', models.FloatField()),
                ('description', models.TextField()),
                ('ideal_age', models.CharField(max_length=50)),
                ('daily_visits', models.PositiveIntegerField()),
                ('innovation_features', models.CharField(max_length=255)),
                ('trustpilot_reviews', models.PositiveIntegerField()),
                ('audience_profile', models.TextField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storytelling_comment', models.TextField()),
                ('site_web', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('gender_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notre site de rencontre partenaire',
                'verbose_name_plural': 'Nos sites de rencontres partenaires',
            },
        ),
    ]
