# Generated by Django 4.2.3 on 2024-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeet',
            name='categorie',
            field=models.CharField(choices=[('Généraliste', 'Site généraliste'), ('Senior', 'Site senior'), ('Haut-de-gamme', 'Site haut-de-gamme')], default='Généraliste', max_length=25),
        ),
        migrations.AlterField(
            model_name='partnermeet',
            name='relation',
            field=models.CharField(choices=[('Durables', 'Durables'), ('Homosexuelles', 'Homosexuelles')], default='Toutes', max_length=25),
        ),
    ]
