# Generated by Django 4.2.3 on 2024-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeet',
            name='categorie',
            field=models.CharField(choices=[('Généraliste', 'Site généraliste'), ('Libertin', 'Site libertin'), ('Senior', 'Site senior'), ('Religieux', 'Site religieux'), ('Extra-conjugales', 'Site extra-conjugal'), ('Haut-de-gamme', 'Site haut-de-gamme')], default='Généraliste', max_length=25),
        ),
    ]
