# Generated by Django 4.2.3 on 2024-04-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermeet',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='partnermeet',
            name='storytelling_comment',
        ),
    ]
