# Generated by Django 4.2.3 on 2024-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeet',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
