# Generated by Django 4.2.3 on 2024-05-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0002_alter_partnermeet_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
