# Generated by Django 4.2.3 on 2025-01-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0002_partnermeet_countries_partnermeet_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeet',
            name='countries',
            field=models.CharField(choices=[('France', 'FRA'), ('Australia', 'AUS'), ('United States', 'USA'), ('United Kingdom', 'UK'), ('Canada', 'CAN')], default='France', max_length=25),
        ),
    ]
