# Generated by Django 4.2.3 on 2024-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0002_partnermeet_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeet',
            name='co2',
            field=models.BooleanField(default=False),
        ),
    ]
