# Generated by Django 4.2.3 on 2024-05-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0002_alter_partnermeet_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermeet',
            name='date_creation',
        ),
    ]
