# Generated by Django 4.2.3 on 2024-05-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0003_lightener'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightener',
            options={'verbose_name': 'Adresse IP', 'verbose_name_plural': 'Adresse IP'},
        ),
    ]
