# Generated by Django 4.2.3 on 2025-01-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0003_alter_partnermeet_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnermeet',
            old_name='Visites_France',
            new_name='Visites',
        ),
        migrations.AlterField(
            model_name='partnermeet',
            name='countries',
            field=models.CharField(choices=[('France', 'FRA'), ('Australia', 'AUS'), ('United States', 'USA'), ('Belgium', 'BEL'), ('United Kingdom', 'UK'), ('Canada', 'CAN')], default='France', max_length=25),
        ),
    ]
