# Generated by Django 4.2.3 on 2024-05-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0004_alter_lightener_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lightener',
        ),
    ]
