# Generated by Django 4.2.3 on 2025-02-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0005_alter_partnermeet_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermeet',
            name='flag',
        ),
    ]
