# Generated by Django 4.2.3 on 2024-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0006_alter_partnermeet_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermeet',
            name='age',
            field=models.CharField(choices=[('18-30', '18-30 '), ('31-45', '31-45 '), ('+ 46', '+ 46')], max_length=50),
        ),
    ]
