# Generated by Django 4.2.3 on 2025-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0006_remove_partnermeet_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeet',
            name='affiliation_adulte',
            field=models.BooleanField(default=False),
        ),
    ]
