# Generated by Django 4.2.3 on 2025-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0007_partnermeet_affiliation_adulte'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeet',
            name='categories',
            field=models.CharField(choices=[('Jeune', 'Site pour jeunes'), ('Géolocalisation', 'Géolocalisation'), ('Interculturelles', 'Interculturelles'), ('Femme ronde', 'Femme ronde'), ('Discrétion', 'Discrétion')], default='Géolocalisation', max_length=25),
        ),
        migrations.AddField(
            model_name='partnermeet',
            name='relations',
            field=models.CharField(choices=[('Adultère', 'Adultère'), ('Lesbienne', 'Lesbienne'), ('Gay', 'Gay'), ('Interculturelles', 'Interculturelles')], default='Toutes', max_length=25),
        ),
        migrations.AlterField(
            model_name='partnermeet',
            name='relation',
            field=models.CharField(choices=[('Durables', 'Durables'), ('Amicales', 'Amicales'), ('LGBTQ+', 'LGBTQ+')], default='Toutes', max_length=25),
        ),
    ]
