# Generated by Django 4.2.3 on 2025-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_meet', '0008_partnermeet_categories_partnermeet_relations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermeet',
            name='FLAG',
            field=models.ImageField(blank=True, null=True, upload_to='Countries/'),
        ),
    ]
