# Generated by Django 3.2.3 on 2024-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='legal_Controler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Legal', models.TextField(default=' ', max_length=500)),
            ],
            options={
                'verbose_name': 'Notre document juridique',
                'verbose_name_plural': 'Nos documents juridiques',
            },
        ),
    ]
