# Generated by Django 4.2.3 on 2024-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_legal_delete_legal_controler'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consenti'),
        ),
    ]
