# Generated by Django 4.2.3 on 2024-05-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_legal_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='consent',
        ),
    ]
