# Generated by Django 4.2.3 on 2024-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_remove_legal_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consenti'),
        ),
    ]
