# Generated by Django 4.2.3 on 2024-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comment',
            field=models.CharField(default=False, max_length=500, unique=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Liké'),
        ),
    ]
