# Generated by Django 4.2.3 on 2024-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
