# Generated by Django 4.2.3 on 2024-07-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_comment_blogpost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
    ]
