# Generated by Django 4.2.3 on 2024-05-10 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lightener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('birth', models.DateField(null=True)),
                ('prenom', models.CharField(default='', max_length=25)),
                ('consentement', models.BooleanField(default=False)),
                ('weekly_likes', models.PositiveIntegerField(default=0)),
                ('weekly_favorites', models.PositiveIntegerField(default=0)),
                ('last_weekly_reset', models.DateField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('engagement', models.PositiveIntegerField(default=0)),
                ('favorite_app', models.PositiveIntegerField(default=0)),
                ('clic_comparer', models.PositiveIntegerField(default=0)),
                ('clic_rencontres', models.PositiveIntegerField(default=0)),
                ('clic_therapeutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Notre compte utilisateur',
                'verbose_name_plural': 'Nos comptes utilisateurs',
            },
        ),
    ]
