# Generated by Django 4.2.3 on 2024-05-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Le visiteur de Lightmeet', 'verbose_name_plural': 'Les visiteurs de Lightmeet'},
        ),
    ]
