# Generated by Django 4.2.3 on 2024-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Informations', 'Je souhaite en savoir plus'), ('Delta Voicer', 'Comment enregistrer sa voix ?'), ('Technique', 'Soucis technique sur la plateforme')], default='', max_length=25)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notre contact avec le client',
                'verbose_name_plural': 'Nos contacts avec les clients',
            },
        ),
    ]
